language: ruby
cache: bundler
rvm:
  - 2.2.3

bundler_args: --without production

services:
  - postgresql

addons:
  postgresql: "9.3"
  code_climate:
    repo_token: f8eae6a8fbcf0987deff8501d2d8a471060b78c18952cdafc9cd24ebc86d395c

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres